### ISSUE TITLE
Cannot set self-destruct pin in initial setup on windows

### ISSUE THREAD

**Issue by tasso85** [trustcrypto/OnlyKey-App#118]
Hi, I have just noticed a problem when setting the self destruct pin in the initial setup phase using the OnlyKey App on windows 10.

Specifically, the steps I follow are:
1. enter new PIN, tick checkbox and click next
2. re-enter PIN and click next
3. "I don't want a second profile"
4. I now try to enter a self-destruct PIN, but no matter what, it won't go after this screen when I click next, and the "last message" will always be one of "canceled", "enter self-destruct pin" or "re-enter self-destruct pin"

I am sure I correctly entered the pin each and every time, as I saw the led blink at each input; I have only been able to set the self-destruct pin by first skipping this step and going to the end of the initial setup, and then re-programming the self-destruct pin only.

**Comment by basnappl** [comment]
I had trouble with this too because the instructions aren't very clear.  What you are supposed to do is, on the "Setup" tab in the app, put the OnlyKey into config mode as it instructs, then:

1. Click the "Change Self-Destruct PIN" button
2. Check the checkbox
3. Enter your new 7-10 digit PIN
4. Click "Submit"
5. Re-enter your new 7-10 digit PIN
6. Click "Submit"

So, I think where you are going wrong is by hitting "Submit" _before_ you enter the new PIN for the first time.  Try it again, enter the new PIN before hitting "Submit" for the first time.

**Comment by tasso85** [comment]
Thanks for the tip (and sorry for the very late reply), however I am pretty sure I followed the procedure as you describe it.

Anyway, I just tried again with a new key, and it seems to have worked properly, perhaps it was a problem of that specific key itself?
