### ISSUE TITLE
Problems with gui not responding 

### ISSUE THREAD

**Issue by yuperi** [trustcrypto/OnlyKey-App#198]
Ubuntu 22.04, ver 5.3.4
Gui button stop responding after closing window
Please check the video

https://user-images.githubusercontent.com/32847814/167988845-9b81005b-e9b9-43f1-89a0-c468d721c4e2.mp4

**Comment by maaft** [comment]
same issue. Is there any work being done here?

**Comment by onlykey** [comment]
@maaft We are looking for a solution but so far no luck. The native file load in the app on the latest Ubuntu causes the app to stop working and requires restarting the app. This happens when trying to load firmware or save backup. There are no errors in the app or Ubuntu so we are not sure what changes in Ubuntu 22 are causing this.

**Comment by maaft** [comment]
@onlykey in 8 months knowing this, you could have implemented a CLI version of restore/firmware-upgrade.

off-topic:
any plans to migrate away from (untyped) python / javascript to typesafe alternatives like golang / typescript?

**Comment by onlykey** [comment]
We have published release here to address this issue:
https://github.com/trustcrypto/OnlyKey-App/releases/tag/v5.5.0

**Comment by rodgolpe** [comment]
Fixed by #210.
