### ISSUE TITLE
OnlyKey App cannot connect after Windows 10 1903 feature update

### ISSUE THREAD

**Issue by dcashion** [trustcrypto/OnlyKey-App#95]
After 1903 feature update the OnlyKey app cannot connect to the OnlyKey.  I've tried rebooting and updating the Windows 10 driver.  The device is properly recognized by Windows. Before this the OnlyKey and Yubikey have cohabitated happily (I use both to access my password manager). I have tried to remove both keys and insert the OnlyKey alone.

At this time the issue is that I cannot access any of the config feature.  Function as a key appears to be unaffected.

A full system info file is available upon request.

![image](https://user-images.githubusercontent.com/22311080/56078714-8d6b0200-5da8-11e9-80cd-2ce5a86c210c.png)

![image](https://user-images.githubusercontent.com/22311080/56078768-13874880-5da9-11e9-849a-cff6acb1fd5b.png)

![image](https://user-images.githubusercontent.com/22311080/56078612-521c0380-5da7-11e9-8134-54eb55fd1c10.png)

OS Name	Microsoft Windows 10 Home
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	
System Manufacturer	Dell Inc.
System Model	Inspiron 5565
System Type	x64-based PC
System SKU	0769
Processor	AMD A12-9700P RADEON R7, 10 COMPUTE CORES 4C+6G, 2500 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.1.1, 17-Jul-17
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0021CT
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	
Hardware Abstraction Layer	Version = "10.0.18362.1"
User Name	
Time Zone	
Installed Physical Memory (RAM)	12.0 GB
Total Physical Memory	11.0 GB
Available Physical Memory	5.44 GB
Total Virtual Memory	13.2 GB
Available Virtual Memory	5.67 GB
Page File Space	2.25 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by onlykey** [comment]
@dcashion I will try the update to see if I can reproduce this. One thing to try would be the chrome app - https://chrome.google.com/webstore/detail/onlykey-configuration/adafilbceehejjehoccladhbkgbjmica?hl=en-US

If the chrome app works and the native app doesn't that would mean the USB drivers are OK and maybe a reinstall of the native app would fix the issue.

**Comment by dcashion** [comment]
Tried your suggerstion with no effectt.  Just to be sure I uninstalled both the app and the chrome app.  Reinstalled the Chrome app. No joy.  Reinstalled the Windows app.  Again, no joy.

Any other thoughts?

**Comment by politick** [comment]
Have you tried to use your key normally ?  I have a computer and one phone where when I connect the key the LED does not flash or respond to key presses.  But if I wait the "normal OnlyKey boot time" (about 2 seconds) and then I enter my PIN, then my passwords work but WITHOUT the LED ever working.  The key looks dead, but it's not; really annoying.

**Comment by dcashion** [comment]
Just the app is not working.  The normal functionlity is fine.  I did miss the memo that says that an OnlyKey has to be plugged into the computer - it will not work plugged into a hub.

**Comment by tekzer0** [comment]
Mine's doing crazier stuff and is brand new and has only got me past the insert onlykey logo once and that's when I unplugged the onlykey. I guess I have been posting the longer versions of this issue fully explained in the incorrect place and have no idea how to get back to that spot to post all the details over again here because I went through a lot including the one time I could get the chrome app (never the program) to recognize it, after unplugging it of all things & plugging it back in quickly when I saw that the red logo went away, then it wouldn't let me confirm a pin so I upgraded to the most current firmware and in back to square one with it not being recognized by either app or program. To specify I'm on the slow circle as a Windows 10 insider and amusing no hub and a z270 motherboard and USB 3 slot. I had just purchased it in my brand new in from the official store on Amazon and it took weeks for me to get it to actually let me past the annoying red logo to insert it after hundreds of times of putting it in taking it out and trying different ports. and I repeat the only time I got past that logo was after removing it and the only thing different that time which I haven't been able to repeat, was the yubikey authenticator app was open. And no, the yubikey was not inserted at the time.

**Comment by onlykey** [comment]
@tekzer0 Have you tried it on a different computer?

**Comment by takd** [comment]
I can confirm that the same thing happens on my computer as with @dcashion. The key works well, but the desktop app cannot communicate with it after the Windows 10 May Update (build 1903).

**Comment by onlykey** [comment]
@takd This issue is also being tracked here - https://groups.google.com/forum/#!msg/onlykey/HBhRk1BXSp0/4qd7fGTZAQAJ

I was able to reproduce the issue on the insider preview of Windows 10. I found that if you run the app as administrator it works but otherwise it seems Windows is preventing communication with USB device. I need to investigate further to find why Windows now requires admin privileges to communicate with USB device. Other user's have verified that running the app as admin works. Unfortunately this is not just a problem with our app we can fix, the issue appears to be that Windows is now blocking USB HID communication by all apps without admin privileges.

**Comment by c99d45** [comment]
@onlykey any update? Haven't seen activity here or google groups for weeks...
my TOTP slots have not been working since the 1903 feature update (they just return NOTSET), which is a bit of a pain. I believe this is related to this issue? I can confirm that on my machine the onlykey app does not recognise the device, even when launched as administrator.

**Comment by onlykey** [comment]
@c99d45 We have been able to reproduce the issue on Win 10 1903 where you have to run the app as admin. If running the app as admin does not work for you then this must be a different issue you are seeing. You are using the OnlyKey Desktop app right? You can't run the chrome app as admin.

**Comment by c99d45** [comment]
Thanks @onlykey. My mistake; it's the Chrome app that I have installed😖.
I suppose the chrome app is also victim to this new MS policy.

**Comment by onlykey** [comment]
@c99d45 Yes, unfortunately all USB HID communication is blocked in the latest Windows. We have a solution I am working hard on but it requires a different mode of communication.

**Comment by M-Pixel** [comment]
@onlykey did you read somewhere that 1903 is blocking _all_ USB-HID communication, not just devices that are detected as FIDO?  If so, could you link to that source?  Unfortunately, there's not much info yet on this issue.

**Comment by brandybrice** [comment]
You need to actually launch this app in administrator mode to make it "work".

**Comment by riedel** [comment]
> @c99d45 Yes, unfortunately all USB HID communication is blocked in the latest Windows. We have a solution I am working hard on but it requires a different mode of communication.

Since this issues was closed is there any progress or another issue tracking this?

**Comment by onlykey** [comment]
@riedel The issue was fixed in the latest app release 5.2.0 with the latest firmware.
